version: '3.8'
services:
  api:
    build: ./api
    container_name: backend
    env_file: .env
    ports:
      - '5555:5555'
    volumes:
      - ./api:/app
      - ./app/node_modules

  # mongo:
  #   image: mongo
  #   container_name: mongo_stack_mongo_1
  #   restart: always
  #   ports:
  #     - '27017:27017'
  mongo:
    image: mongo
    container_name: mongo_stack_mongo_1
    hostname: fuldagateway.ddns.net
    domainname: services.local
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo

