export const input_params_dict = {
  database_location: "remote",
  database_type: "timeseries",
  local_database_name: "netflowtest",
  remote_database_name: "netflow",
  structured_collection_name: "netflow",
  collection_name: "nts",
  local_database_url: "localhost",
  local_database_port: 27017,
  remote_database_url: "172.25.3.101",
  remote_database_port: 27017,
  start_time: null,
  end_time: null,
  data_limit: 50000000,
  num_entries: 30,
  sample_size: null,
  window: 24,
  structured_field_dict: {
    flow_id: "$netflow.flow_id",
    timestamp: "$@timestamp",
    network_transport: { $ifNull: ["$network.transport", "unknown"] },
    destination_ip: { $ifNull: ["$destination.ip", "unknown"] },
    destination_port: { $ifNull: ["$destination.port", "unknown"] },
    source_ip: { $ifNull: ["$source.ip", "unknown"] },
    source_port: { $ifNull: ["$source.port", "unknown"] },
    destination_bytes: { $ifNull: ["$destination.bytes", 0] },
    source_bytes: { $ifNull: ["$source.bytes", 0] },
    network_bytes: { $ifNull: ["$network.bytes", 0] },
    flow_locality: { $ifNull: ["$flow.locality", "unknown"] },
    agent_name: { $ifNull: ["$agent.name", "unknown"] },
    network_direction: { $ifNull: ["$network.direction", "unknown"] },
    network_exporter_version: {
      $ifNull: ["$netflow.exporter.version", "unknown"],
    },
    netflow_ingress_interface: {
      $ifNull: ["$netflow.ingress_interface", "unknown"],
    },
    netflow_egress_interface: {
      $ifNull: ["$netflow.egress_interface", "unknown"],
    },
    _id: 0,
  },
  timeseries_field_dict: {
    timestamp: "$timestamp",
    network_transport: "$network_transport",
    destination_ip: "$destination_ip",
    destination_port: "$destination_port",
    source_ip: "$source_ip",
    source_port: "$source_port",
    destination_bytes: "$destination_bytes",
    source_bytes: "$source_bytes",
    network_bytes: "$network_bytes",
    flow_locality: "$flow_locality",
    source_locality: "$source_locality",
    destination_locality: "$destination_locality",
    _id: 0,
  },
  db_asn: "src/utils/GeoLite2-ASN.mmdb",
  db_city: "src/utils/GeoLite2-City.mmdb",
  db_country: "src/utils/GeoLite2-Country.mmdb",
  geo_lookup_dict: {
    "51.2993,9.491": ["Germany", "Kassel"],
    "50.0027,8.2788": ["Germany", "Mainz"],
    "34.7732,113.722": ["China", "Zhengzhou"],
    "22.2578,114.1657": ["Hongkong", "Hongkong"],
    "55.7386,37.6068": ["Russia", "Moscow"],
    "37.751,-97.822": ["United States", "Cheney"],
    "47.6034,-122.3414": ["United States", "Seattle"],
    "45.5248,-122.6789": ["United States", "Portland"],
  },
};
